import { supabase } from "./supabase.js";
import { requireAuth } from "./auth.js";
import { escapeHTML, setStatus } from "./utils.js";
import { RARITIES, badgeFrame, badgeExp, rarityInfo, derivedAward } from "./badges.js";
const grid=document.querySelector("#achievements-grid"),status=document.querySelector("#achievements-status"),summary=document.querySelector("#achievement-summary"),e=v=>escapeHTML(String(v??""));
function lockedFrame(b){return `<div class="badge-frame badge-frame-locked" title="Ainda não conquistado">${b?.icon?`<img src="${e(b.icon)}" alt="">`:"✦"}</div>`}
function nextProgress(b,a){if(!a||b.is_mvp||b.progression_mode!=="quantitative")return null;const s=Array.isArray(b.progression_steps)?b.progression_steps.map(Number):[];if(!s.length)return null;const c=Number(a.progress_value||0),r=rarityInfo(a.rarity),i=RARITIES.findIndex(([k])=>k===r.key),next=s[i+1];if(next==null)return{current:c,maxed:true,percent:100};const prev=Number(s[i]||0),span=Math.max(1,next-prev);return{current:c,target:next,maxed:false,percent:Math.max(0,Math.min(100,((c-prev)/span)*100))}}
function card(b,a){const u=!!a,r=u&&!b.is_mvp?rarityInfo(a.rarity):null,p=nextProgress(b,a),exp=u?badgeExp(b,a):0;let state=`<span class="achievement-state locked">Não conquistado</span>`;if(u&&b.is_mvp)state=`<span class="achievement-state special">MVP atual</span>`;else if(u)state=`<span class="achievement-state unlocked">${e(r.label)} · ${exp} EXP</span>`;let ph="";if(!u){const first=Array.isArray(b.progression_steps)&&b.progression_steps.length?b.progression_steps[0]:null;ph=first!=null?`<p class="achievement-next">Primeiro marco: <strong>${e(first)}</strong></p>`:`<p class="achievement-next">Aguardando reconhecimento.</p>`}else if(p){ph=p.maxed?`<div class="achievement-progress maxed"><div class="achievement-progress-label"><span>Progressão máxima</span><strong>${e(p.current)}</strong></div><div class="achievement-progress-track"><span style="width:100%"></span></div></div>`:`<div class="achievement-progress"><div class="achievement-progress-label"><span>Próximo grau</span><strong>${e(p.current)} / ${e(p.target)}</strong></div><div class="achievement-progress-track"><span style="width:${p.percent.toFixed(1)}%"></span></div></div>`}else if(u&&b.progression_mode==="qualitative")ph=`<p class="achievement-next">Progressão concedida por reconhecimento.</p>`;return `<article class="achievement-card ${u?"is-unlocked":"is-locked"} ${b.is_mvp?"is-mvp":""}"><div class="achievement-icon-wrap">${u?badgeFrame(b,a):lockedFrame(b)}</div><div class="achievement-content"><div class="achievement-title-row"><h2>${e(b.name)}</h2>${state}</div><p class="achievement-category">${e(b.category||"Conquista")} · ${b.source_scope==="character"?"Feitos dos personagens":"Feito do jogador"}</p><p class="achievement-description">${(!u&&b.is_secret)?'Conquista secreta. Continue explorando o RPG para revelá-la.':e(b.description||"")}</p>${u&&!b.is_mvp?`<button class="post-edit" data-feature-badge="${b.id}">${a.featured?'★ Em destaque':'☆ Destacar no perfil'}</button>`:''}${ph}</div></article>`}
async function init(){try{const s=await requireAuth();if(!s)return;const [br,pr,cr,cpr]=await Promise.all([supabase.from("badges").select("*").order("name"),supabase.from("player_badges").select("badge_id,rarity,progress_value,featured").eq("player_id",s.user.id),supabase.from("characters").select("id").eq("owner_id",s.user.id),supabase.from("character_badge_progress").select("character_id,badge_id,progress_value")]);for(const r of [br,pr,cr,cpr])if(r.error)throw r.error;const badges=br.data||[],direct=new Map((pr.data||[]).map(a=>[a.badge_id,a])),ids=new Set((cr.data||[]).map(c=>c.id)),sums=new Map();for(const x of cpr.data||[])if(ids.has(x.character_id))sums.set(x.badge_id,(sums.get(x.badge_id)||0)+Number(x.progress_value||0));const by=new Map();for(const b of badges){if(b.source_scope==="character"){const a=derivedAward(b,sums.get(b.id)||0);if(a)by.set(b.id,a)}else if(direct.has(b.id))by.set(b.id,direct.get(b.id))}const unlocked=badges.filter(b=>by.has(b.id)),total=badges.reduce((n,b)=>n+(by.has(b.id)?badgeExp(b,by.get(b.id)):0),0);summary.innerHTML=`<div><strong>${unlocked.length}</strong><span>de ${badges.length} conquistados</span></div><div><strong>${total}</strong><span>EXP em Brasões</span></div>`;grid.innerHTML=badges.map(b=>card(b,by.get(b.id))).join("")||"<p>Nenhum Brasão cadastrado.</p>";grid.querySelectorAll("[data-feature-badge]").forEach(btn=>btn.onclick=async()=>{const{error}=await supabase.rpc("toggle_featured_badge",{p_badge_id:btn.dataset.featureBadge});if(error)alert(error.message);else init()})}catch(err){console.error(err);setStatus(status,err.message||"Não foi possível carregar suas conquistas.","error")}}init();
