import { supabase } from './supabase.js';
import { escapeHTML,getQueryParam,avatarHTML,setStatus } from './utils.js';
const root=document.querySelector('#character-profile'),id=getQueryParam('id');let character=null,viewer=null,isAdmin=false,entries=[],parties=[];const cats={skills:'Habilidades',inventory:'Inventário',history:'História'};const e=v=>escapeHTML(String(v??''));
function ext(v=''){try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}}
async function loadViewer(){const{data:{user}}=await supabase.auth.getUser();viewer=user;if(user){const{data}=await supabase.from('profiles').select('role').eq('id',user.id).maybeSingle();isAdmin=data?.role==='admin'}}
async function load(){await loadViewer();const [cr,pr]=await Promise.all([supabase.from('characters').select(`id,owner_id,name,nickname,description,portrait_url,ficha_url,level,notoriety,reputation,points,status,clan_id,owner:profiles!characters_owner_id_fkey(id,display_name,username,avatar_url),party:clans(id,name,acronym)`).eq('id',id).maybeSingle(),supabase.from('clans').select('id,name').order('name')]);const data=cr.data;if(cr.error||!data||data.status!=='approved'){root.innerHTML='<p class="status error">Personagem não encontrado.</p>';return}character=data;parties=pr.data||[];await reloadEntries(false);render()}
function canManage(){return viewer&&(viewer.id===character.owner_id||isAdmin)}
function entryCard(x){return `<article class="character-entry"><div class="character-entry-head"><h3>${e(x.title)}</h3>${canManage()?`<div><button data-edit-entry="${x.id}" class="post-edit">Editar</button><button data-delete-entry="${x.id}" class="post-delete">Excluir</button></div>`:''}</div>${x.content?`<div class="character-entry-content">${e(x.content).replace(/\n/g,'<br>')}</div>`:''}</article>`}
function editor(cat){return `<form class="character-entry-form" data-entry-form="${cat}"><p class="form-help">Novos registros e alterações passam pela aprovação da administração.</p><input name="title" maxlength="160" placeholder="${cat==='skills'?'Nome da habilidade':cat==='inventory'?'Nome do item':'Título do registro'}" required><textarea name="content" maxlength="100000" rows="7" placeholder="Descrição, efeitos e detalhes..."></textarea><button class="button button-small">Enviar para aprovação</button><p class="status"></p></form>`}
function panel(cat){const list=entries.filter(x=>x.category===cat);return `<section data-character-panel="${cat}" hidden>${canManage()?editor(cat):''}<div class="character-entry-list">${list.map(entryCard).join('')||'<p class="profile-feed-empty">Nenhum registro nesta seção.</p>'}</div></section>`}
function render(){const c=character,o=c.owner||{},sheet=ext(c.ficha_url),mine=viewer?.id===c.owner_id;root.innerHTML=`<section class="character-profile-hero"><div class="avatar character-profile-portrait">${avatarHTML(c.name,c.portrait_url,`Retrato de ${c.name}`)}</div><div><span class="eyebrow">Personagem</span><h1>${e(c.name)}</h1>${c.nickname?`<p class="character-nickname">${e(c.nickname)}</p>`:''}<p>Player: ${o.username?`<a class="mention-link" href="jogador.html?u=${encodeURIComponent(o.username)}">@${e(o.username)}</a>`:e(o.display_name||'Jogador')}</p><div class="meta"><span>Nível ${Number(c.level||1)}</span><span>Fama: ${e(c.notoriety||'Não definida')}</span><span>Reputação: ${e(c.reputation||'Não definida')}</span>${c.party?`<span>Party: ${e(c.party.name)}</span>`:''}</div><div class="form-actions">${sheet?`<a class="button button-small" href="${e(sheet)}" target="_blank" rel="noopener">Ficha externa ↗</a>`:''}${mine&&!isAdmin?`<button class="button button-small" id="request-character-edit">Solicitar edição</button><button class="button button-small button-danger" id="request-character-delete">Solicitar exclusão</button>`:''}</div><p id="character-request-status" class="status"></p></div></section><section class="character-overview"><div class="section-heading"><span class="eyebrow">Visão geral</span><h2>Sobre ${e(c.name)}</h2></div><div class="character-description">${e(c.description||'Nenhuma descrição registrada.').replace(/\n/g,'<br>')}</div></section><section class="section"><div class="character-tabs">${Object.entries(cats).map(([k,v],i)=>`<button class="character-tab ${i?'':'active'}" data-character-tab="${k}">${v}</button>`).join('')}</div>${Object.keys(cats).map(panel).join('')}</section>`;bind();switchTab('skills')}
function switchTab(cat){document.querySelectorAll('[data-character-tab]').forEach(b=>b.classList.toggle('active',b.dataset.characterTab===cat));document.querySelectorAll('[data-character-panel]').forEach(p=>p.hidden=p.dataset.characterPanel!==cat)}
async function request(action,contentId,payload,statusEl){setStatus(statusEl,'Enviando solicitação...');const{error}=await supabase.rpc('submit_character_request',{p_action:action,p_character_id:character.id,p_content_id:contentId||null,p_payload:payload||{}});if(error)return setStatus(statusEl,error.message,'error');setStatus(statusEl,'Solicitação enviada para aprovação.','success')}
function bind(){document.querySelectorAll('[data-character-tab]').forEach(b=>b.onclick=()=>switchTab(b.dataset.characterTab));document.querySelectorAll('[data-entry-form]').forEach(f=>f.onsubmit=addEntry);document.querySelectorAll('[data-edit-entry]').forEach(b=>b.onclick=editEntry);document.querySelectorAll('[data-delete-entry]').forEach(b=>b.onclick=deleteEntry);document.querySelector('#request-character-edit')?.addEventListener('click',editCharacter);document.querySelector('#request-character-delete')?.addEventListener('click',()=>request('delete',null,{},document.querySelector('#character-request-status')))}
async function addEntry(ev){ev.preventDefault();const f=ev.currentTarget,s=f.querySelector('.status'),cat=f.dataset.entryForm;await request('content_create',null,{category:cat,title:f.title.value.trim(),content:f.content.value.trim()||null,position:entries.filter(x=>x.category===cat).length},s);if(!s.classList.contains('error'))f.reset()}
async function editEntry(ev){const x=entries.find(i=>i.id===ev.currentTarget.dataset.editEntry);if(!x)return;const title=prompt('Título proposto:',x.title);if(title===null||!title.trim())return;const content=prompt('Conteúdo proposto:',x.content||'');if(content===null)return;await request('content_update',x.id,{category:x.category,title:title.trim(),content:content.trim()||null,position:x.position||0},document.querySelector(`[data-character-panel="${x.category}"] .status`)||document.querySelector('#character-request-status'))}
async function deleteEntry(ev){const x=entries.find(i=>i.id===ev.currentTarget.dataset.deleteEntry);if(!x||!confirm(`Solicitar exclusão de "${x.title}"?`))return;await request('content_delete',x.id,{},document.querySelector('#character-request-status'))}
async function editCharacter(){const c=character;const name=prompt('Nome proposto:',c.name);if(name===null||!name.trim())return;const nickname=prompt('Alcunha/título:',c.nickname||'');if(nickname===null)return;const description=prompt('Descrição:',c.description||'');if(description===null)return;const portrait_url=prompt('URL do retrato:',c.portrait_url||'');if(portrait_url===null)return;const ficha_url=prompt('Ficha externa:',c.ficha_url||'');if(ficha_url===null)return;const level=prompt('Nível:',String(c.level||1));if(level===null)return;const notoriety=prompt('Fama:',c.notoriety||'Não definida');if(notoriety===null)return;const reputation=prompt('Reputação:',c.reputation||'Não definida');if(reputation===null)return;await request('update',null,{name:name.trim(),nickname:nickname.trim()||null,description:description.trim()||null,portrait_url:portrait_url.trim()||null,ficha_url:ficha_url.trim()||null,level:Number(level)||1,notoriety:notoriety.trim()||'Não definida',reputation:reputation.trim()||'Não definida',clan_id:c.clan_id||null},document.querySelector('#character-request-status'))}
async function reloadEntries(renderAfter=true){const{data}=await supabase.from('character_content').select('*').eq('character_id',id).order('position').order('created_at');entries=data||[];if(renderAfter)render()}
load();