import { supabase } from "./supabase.js";
import { escapeHTML, setStatus, avatarHTML } from "./utils.js";
const adminArea=document.querySelector("#character-admin"), playerArea=document.querySelector("#character-player-create"), accessMessage=document.querySelector("#access-message"), form=document.querySelector("#character-form"), playerForm=document.querySelector("#player-character-form"), playerStatus=document.querySelector("#player-character-status"), message=document.querySelector("#character-status-message"), characterList=document.querySelector("#character-list"), ownerSelect=document.querySelector("#character-owner"), partySelect=document.querySelector("#character-party"), playerParty=document.querySelector("#player-character-party"), cancelButton=document.querySelector("#cancel-edit"), formTitle=document.querySelector("#form-title");
let profiles=[],parties=[],characters=[],viewer=null,viewerProfile=null,isAdmin=false; const esc=v=>escapeHTML(String(v??""));
async function loadProfiles(){const{data,error}=await supabase.from("profiles").select("id,display_name,username,avatar_url").eq("listed",true).order("display_name");if(error)throw error;profiles=data||[];if(ownerSelect)ownerSelect.innerHTML='<option value="">Selecione um jogador</option>'+profiles.map(p=>`<option value="${esc(p.id)}">${esc(p.display_name||p.username||"Jogador")}</option>`).join("")}
async function loadParties(){const{data,error}=await supabase.from("clans").select("id,name").order("name");parties=error?[]:(data||[]);const opts='<option value="">Sem party</option>'+parties.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join("");if(partySelect)partySelect.innerHTML=opts;if(playerParty)playerParty.innerHTML=opts}
async function loadCharacters(){const{data,error}=await supabase.from("characters").select("*").eq("status","approved").order("name");if(error)throw error;characters=data||[];renderCharacters()}
function renderCharacters(){const ordered=[...characters].sort((a,b)=>{const am=viewer?.id===a.owner_id?0:1,bm=viewer?.id===b.owner_id?0:1;return am-bm||String(a.name||"").localeCompare(String(b.name||""),"pt-BR")});characterList.innerHTML=ordered.map(c=>{const owner=profiles.find(p=>p.id===c.owner_id),party=parties.find(p=>p.id===c.clan_id),mine=viewer?.id===c.owner_id;return `<article class="player-card character-mini-card ${mine?"character-card-owned":"character-card-community"}"><a class="character-card-main" href="/personagem?id=${encodeURIComponent(c.id)}"><div class="avatar">${avatarHTML(c.name,c.portrait_url,`Retrato de ${c.name}`)}</div><div class="character-mini-info"><h3>${esc(c.name)}</h3><p>Player: ${esc(owner?.display_name||owner?.username||"Jogador")}</p>${party?`<p>Party: ${esc(party.name)}</p>`:""}</div></a>${isAdmin?`<div class="character-card-actions"><button class="button button-small" data-edit="${c.id}">Editar direto</button><button class="button button-small" data-delete="${c.id}">Excluir direto</button></div>`:""}</article>`}).join("")||"<p>Nenhum personagem aprovado.</p>"}
function attr(fd,key){const v=Number(fd.get(key)||0);return Number.isFinite(v)?Math.max(0,Math.trunc(v)):0}
function payload(fd,owner){return {name:String(fd.get("name")||"").trim(),nickname:String(fd.get("nickname")||"").trim()||null,owner_id:owner,description:String(fd.get("description")||"").trim()||null,portrait_url:String(fd.get("portrait_url")||"").trim()||null,ficha_url:String(fd.get("ficha_url")||"").trim()||null,level:Number(fd.get("level")||1),notoriety:String(fd.get("notoriety")||"").trim()||"Não definida",reputation:String(fd.get("reputation")||"").trim()||"Não definida",clan_id:String(fd.get("clan_id")||"")||null,strength:attr(fd,"strength"),vitality:attr(fd,"vitality"),wisdom:attr(fd,"wisdom"),speed:attr(fd,"speed"),spirit:attr(fd,"spirit")}}
document.querySelector('#save-character-draft')?.addEventListener('click',async()=>{if(!viewer)return location.href='/login';const p=payload(new FormData(playerForm),viewer.id);const{data:old}=await supabase.from('character_drafts').select('id').eq('owner_id',viewer.id).is('character_id',null).maybeSingle();const r=old?await supabase.from('character_drafts').update({payload:p,updated_at:new Date().toISOString()}).eq('id',old.id):await supabase.from('character_drafts').insert({owner_id:viewer.id,payload:p});setStatus(playerStatus,r.error?r.error.message:'Rascunho salvo. Você pode continuar depois.',r.error?'error':'success')});
playerForm?.addEventListener("submit",async e=>{e.preventDefault();if(!viewer)return location.href="/login";const p=payload(new FormData(playerForm),viewer.id);setStatus(playerStatus,"Enviando solicitação...");const{error}=await supabase.rpc("submit_character_request",{p_action:"create",p_character_id:null,p_content_id:null,p_payload:p});if(error)return setStatus(playerStatus,error.message,"error");playerForm.reset();playerForm.level.value=1;["strength","vitality","wisdom","speed","spirit"].forEach(k=>{if(playerForm.elements[k])playerForm.elements[k].value=0});setStatus(playerStatus,"Solicitação enviada. A administração precisa aprovar antes da publicação.","success")});
function resetForm(){form?.reset();if(!form)return;form.id.value="";form.level.value=1;["strength","vitality","wisdom","speed","spirit"].forEach(k=>{if(form.elements[k])form.elements[k].value=0});if(form.points)form.points.value=0;form.status.value="approved";formTitle.textContent="Novo Personagem (admin)";cancelButton.hidden=true}
function editCharacter(id){const c=characters.find(x=>x.id===id);if(!c)return;for(const[k,v]of Object.entries(c))if(form.elements[k])form.elements[k].value=v??"";formTitle.textContent="Editar personagem (admin)";cancelButton.hidden=false;form.scrollIntoView({behavior:"smooth"})}
async function deleteCharacter(id){if(!confirm("Excluir diretamente este personagem?"))return;const{error}=await supabase.from("characters").delete().eq("id",id);if(error)return alert(error.message);await loadCharacters()}
form?.addEventListener("submit",async e=>{e.preventDefault();const fd=new FormData(form),id=String(fd.get("id")||""),p={...payload(fd,String(fd.get("owner_id")||"")),points:Number(fd.get("points")||0),status:String(fd.get("status")||"approved")};const r=id?await supabase.from("characters").update(p).eq("id",id):await supabase.from("characters").insert(p);if(r.error)return setStatus(message,r.error.message,"error");setStatus(message,"Personagem salvo diretamente pela administração.","success");resetForm();await loadCharacters()});
cancelButton?.addEventListener("click",resetForm);characterList?.addEventListener("click",e=>{const a=e.target.closest("[data-edit]"),d=e.target.closest("[data-delete]");if(a)editCharacter(a.dataset.edit);if(d)deleteCharacter(d.dataset.delete)});
(async()=>{try{const{data:{user}}=await supabase.auth.getUser();viewer=user;if(user){const{data}=await supabase.from("profiles").select("role,active,display_name,username").eq("id",user.id).maybeSingle();viewerProfile=data||null;isAdmin=data?.role==="admin";if(data?.active)playerArea.hidden=isAdmin;const ownerBox=document.querySelector("#player-character-owner");if(ownerBox)ownerBox.textContent=`${data?.display_name||data?.username||"Jogador"}${data?.username?` (@${data.username})`:""}`;}adminArea.hidden=!isAdmin;accessMessage.hidden=true;await Promise.all([loadProfiles(),loadParties()]);if(viewer&&!isAdmin){const{data:d}=await supabase.from('character_drafts').select('payload').eq('owner_id',viewer.id).is('character_id',null).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(d?.payload)for(const[k,v]of Object.entries(d.payload))if(playerForm?.elements[k])playerForm.elements[k].value=v??''}await loadCharacters()}catch(err){characterList.innerHTML=`<p class="status error">${esc(err.message)}</p>`}})();