import { supabase } from './supabase.js';
import { escapeHTML,getQueryParam,avatarHTML,setStatus } from './utils.js';
import { RARITIES } from './badges.js';
const root=document.querySelector('#character-profile'),id=getQueryParam('id');let character=null,viewer=null,isAdmin=false,entries=[],parties=[];const cats={skills:'Habilidades',inventory:'Inventário',history:'História'};const e=v=>escapeHTML(String(v??''));
function ext(v=''){try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}}
async function loadViewer(){const{data:{user}}=await supabase.auth.getUser();viewer=user;if(user){const{data}=await supabase.from('profiles').select('role').eq('id',user.id).maybeSingle();isAdmin=data?.role==='admin'}}
async function load(){await loadViewer();const [cr,pr]=await Promise.all([supabase.from('characters').select(`id,owner_id,name,nickname,description,quote,portrait_url,ficha_url,level,notoriety,reputation,points,status,clan_id,scene_sort_mode,owner:profiles!characters_owner_id_fkey(id,display_name,username,avatar_url),party:clans(id,name,acronym)`).eq('id',id).maybeSingle(),supabase.from('clans').select('id,name').order('name')]);const data=cr.data;if(cr.error||!data||data.status!=='approved'){root.innerHTML='<p class="status error">Personagem não encontrado.</p>';return}character=data;parties=pr.data||[];await reloadEntries(false);render();await loadExtras()}
function canManage(){return viewer&&(viewer.id===character.owner_id||isAdmin)}
function entryCard(x){return `<article class="character-entry"><div class="character-entry-head"><h3>${e(x.title)}</h3>${canManage()?`<div><button data-edit-entry="${x.id}" class="post-edit">Editar</button><button data-delete-entry="${x.id}" class="post-delete">Excluir</button></div>`:''}</div>${x.content?`<div class="character-entry-content">${e(x.content).replace(/\n/g,'<br>')}</div>`:''}</article>`}
function editor(cat){return `<form class="character-entry-form" data-entry-form="${cat}"><p class="form-help">Este conteúdo fará parte da página oficial do personagem. Novos registros e alterações só aparecem publicamente após aprovação da administração.</p><input name="title" maxlength="160" placeholder="${cat==='skills'?'Nome da habilidade ou técnica':cat==='inventory'?'Nome do item ou equipamento':'Título do registro histórico'}" required><textarea name="content" maxlength="100000" rows="7" placeholder="Descreva de forma clara o funcionamento, efeitos, características e demais informações relevantes."></textarea><button class="button button-small">Enviar para aprovação</button><p class="status"></p></form>`}
function panel(cat){const list=entries.filter(x=>x.category===cat);return `<section data-character-panel="${cat}" hidden>${canManage()?editor(cat):''}<div class="character-entry-list">${list.map(entryCard).join('')||'<p class="profile-feed-empty">Nenhum registro nesta seção.</p>'}</div></section>`}
function render(){const c=character,o=c.owner||{},sheet=ext(c.ficha_url),mine=viewer?.id===c.owner_id;root.innerHTML=`<section class="character-profile-hero"><div class="avatar character-profile-portrait">${avatarHTML(c.name,c.portrait_url,`Retrato de ${c.name}`)}</div><div><span class="eyebrow">Personagem</span><h1>${e(c.name)}</h1>${c.nickname?`<p class="character-nickname">${e(c.nickname)}</p>`:''}${c.quote?`<blockquote class="character-quote">“${e(c.quote)}”</blockquote>`:''}<p>Player: ${o.username?`<a class="mention-link" href="jogador.html?u=${encodeURIComponent(o.username)}">@${e(o.username)}</a>`:e(o.display_name||'Jogador')}</p><div class="meta"><span>Nível ${Number(c.level||1)}</span><span>Fama: ${e(c.notoriety||'Não definida')}</span><span>Reputação: ${e(c.reputation||'Não definida')}</span>${c.party?`<span>Party: ${e(c.party.name)}</span>`:''}</div><div class="form-actions">${sheet?`<a class="button button-small" href="${e(sheet)}" target="_blank" rel="noopener">Ficha externa ↗</a>`:''}${canManage()?`<button class="button button-small" id="request-character-edit">${isAdmin?'Editar personagem':'Solicitar edição'}</button>${isAdmin?'':`<button class="button button-small button-danger" id="request-character-delete">Solicitar exclusão</button>`}${isAdmin?`<button class="button button-small" id="manage-character-badges">Gerenciar Brasões</button>`:mine?`<button class="button button-small" id="request-badge-progress">Registrar progresso</button>`:''}`:''}</div><p id="character-request-status" class="status"></p></div></section><section class="character-overview"><div class="section-heading"><span class="eyebrow">Visão geral</span><h2>Sobre ${e(c.name)}</h2></div><div class="character-description">${e(c.description||'Nenhuma descrição registrada.').replace(/\n/g,'<br>')}</div></section><section class="section"><div class="character-tabs">${Object.entries(cats).map(([k,v],i)=>`<button class="character-tab ${i?'':'active'}" data-character-tab="${k}">${v}</button>`).join('')}</div>${Object.keys(cats).map(panel).join('')}</section>`;bind();switchTab('skills')}
function switchTab(cat){document.querySelectorAll('[data-character-tab]').forEach(b=>b.classList.toggle('active',b.dataset.characterTab===cat));document.querySelectorAll('[data-character-panel]').forEach(p=>p.hidden=p.dataset.characterPanel!==cat)}
async function request(action,contentId,payload,statusEl){setStatus(statusEl,'Enviando solicitação...');const{error}=await supabase.rpc('submit_character_request',{p_action:action,p_character_id:character.id,p_content_id:contentId||null,p_payload:payload||{}});if(error)return setStatus(statusEl,error.message,'error');setStatus(statusEl,'Solicitação enviada para aprovação.','success')}
function bind(){document.querySelectorAll('[data-character-tab]').forEach(b=>b.onclick=()=>switchTab(b.dataset.characterTab));document.querySelectorAll('[data-entry-form]').forEach(f=>f.onsubmit=addEntry);document.querySelectorAll('[data-edit-entry]').forEach(b=>b.onclick=editEntry);document.querySelectorAll('[data-delete-entry]').forEach(b=>b.onclick=deleteEntry);document.querySelector('#request-character-edit')?.addEventListener('click',editCharacter);document.querySelector('#request-character-delete')?.addEventListener('click',()=>request('delete',null,{},document.querySelector('#character-request-status')));document.querySelector('#manage-character-badges')?.addEventListener('click',openCharacterBadgeManager);document.querySelector('#request-badge-progress')?.addEventListener('click',openBadgeProgressRequest)}
async function addEntry(ev){ev.preventDefault();const f=ev.currentTarget,s=f.querySelector('.status'),cat=f.dataset.entryForm;await request('content_create',null,{category:cat,title:f.title.value.trim(),content:f.content.value.trim()||null,position:entries.filter(x=>x.category===cat).length},s);if(!s.classList.contains('error'))f.reset()}
async function editEntry(ev){const x=entries.find(i=>i.id===ev.currentTarget.dataset.editEntry);if(!x)return;const title=prompt('Título proposto:',x.title);if(title===null||!title.trim())return;const content=prompt('Conteúdo proposto:',x.content||'');if(content===null)return;await request('content_update',x.id,{category:x.category,title:title.trim(),content:content.trim()||null,position:x.position||0},document.querySelector(`[data-character-panel="${x.category}"] .status`)||document.querySelector('#character-request-status'))}
async function deleteEntry(ev){const x=entries.find(i=>i.id===ev.currentTarget.dataset.deleteEntry);if(!x||!confirm(`Solicitar exclusão de "${x.title}"?`))return;await request('content_delete',x.id,{},document.querySelector('#character-request-status'))}
async function editCharacter(){
 const c=character,modal=document.createElement('div');modal.className='modal-backdrop';
 modal.innerHTML=`<div class="modal-panel"><div class="modal-head"><div><span class="eyebrow">${isAdmin?'Administração':'Solicitação de alteração'}</span><h2>Editar ${e(c.name)}</h2></div><button class="modal-close" type="button" aria-label="Fechar">×</button></div><form id="character-edit-form"><div class="character-edit-grid"><div class="field span-2"><label>Nome</label><input name="name" required value="${e(c.name)}"></div><div class="field span-2"><label>Alcunha ou título</label><input name="nickname" value="${e(c.nickname||'')}"></div><div class="field"><label>Player</label><div class="locked-field">${e(c.owner?.display_name||c.owner?.username||'Jogador')}</div></div><div class="field"><label>Party</label><select name="clan_id"><option value="">Sem party</option>${parties.map(p=>`<option value="${e(p.id)}" ${p.id===c.clan_id?'selected':''}>${e(p.name)}</option>`).join('')}</select></div><div class="field"><label>Nível</label><input name="level" type="number" min="1" value="${Number(c.level||1)}"></div><div class="field"><label>Fama</label><input name="notoriety" value="${e(c.notoriety||'')}"></div><div class="field"><label>Reputação</label><input name="reputation" value="${e(c.reputation||'')}"></div><div class="field span-2"><label>URL do retrato</label><input name="portrait_url" type="url" value="${e(c.portrait_url||'')}"></div><div class="field span-2"><label>Ficha externa</label><input name="ficha_url" type="url" value="${e(c.ficha_url||'')}"></div><div class="field span-full"><label>Citação</label><input name="quote" value="${e(c.quote||'')}"></div><div class="field span-full"><label>Descrição</label><textarea name="description" rows="6">${e(c.description||'')}</textarea></div></div><div class="form-actions character-form-actions"><button class="button" type="submit">${isAdmin?'Salvar alterações':'Enviar para aprovação'}</button><button class="button button-small" type="button" data-close>Cancelar</button></div><p class="status"></p></form></div>`;
 document.body.appendChild(modal);const close=()=>modal.remove();modal.querySelector('.modal-close').onclick=close;modal.querySelector('[data-close]').onclick=close;modal.addEventListener('click',ev=>{if(ev.target===modal)close()});
 modal.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const form=ev.currentTarget,fd=new FormData(form),status=form.querySelector('.status'),payload={name:String(fd.get('name')||'').trim(),nickname:String(fd.get('nickname')||'').trim()||null,description:String(fd.get('description')||'').trim()||null,quote:String(fd.get('quote')||'').trim()||null,portrait_url:String(fd.get('portrait_url')||'').trim()||null,ficha_url:String(fd.get('ficha_url')||'').trim()||null,level:Number(fd.get('level')||1),notoriety:String(fd.get('notoriety')||'').trim()||'Não definida',reputation:String(fd.get('reputation')||'').trim()||'Não definida',clan_id:String(fd.get('clan_id')||'')||null};setStatus(status,isAdmin?'Salvando...':'Enviando solicitação...');if(isAdmin){const{error}=await supabase.from('characters').update(payload).eq('id',character.id);if(error)return setStatus(status,error.message,'error');Object.assign(character,payload);setStatus(status,'Personagem atualizado.','success');setTimeout(()=>{close();render()},350)}else{const{error}=await supabase.rpc('submit_character_request',{p_action:'update',p_character_id:character.id,p_content_id:null,p_payload:payload});if(error)return setStatus(status,error.message,'error');setStatus(status,'Solicitação enviada para aprovação.','success')}};
}

async function openBadgeProgressRequest(){
 if(!viewer||viewer.id!==character.owner_id||isAdmin)return;
 const modal=document.createElement('div');modal.className='modal-backdrop';modal.innerHTML=`<div class="modal-panel"><div class="modal-head"><div><span class="eyebrow">Progressão</span><h2>Registrar progresso</h2><p class="form-help">Informe o total atual do feito. A alteração só se torna oficial depois da aprovação da administração.</p></div><button class="modal-close" type="button">×</button></div><div id="badge-progress-request"><p class="status">Carregando...</p></div></div>`;document.body.appendChild(modal);const close=()=>modal.remove();modal.querySelector('.modal-close').onclick=close;modal.addEventListener('click',ev=>{if(ev.target===modal)close()});const box=modal.querySelector('#badge-progress-request');
 const [br,pr]=await Promise.all([supabase.from('badges').select('id,name,description,progression_steps').eq('source_scope','character').eq('progression_mode','quantitative').order('name'),supabase.from('character_badge_progress').select('badge_id,progress_value').eq('character_id',character.id)]);if(br.error||pr.error){box.innerHTML=`<p class="status error">${e((br.error||pr.error).message)}</p>`;return}const badges=br.data||[],current=new Map((pr.data||[]).map(x=>[x.badge_id,Number(x.progress_value||0)]));
 if(!badges.length){box.innerHTML='<p class="profile-feed-empty">Nenhum Brasão quantitativo de personagem está disponível.</p>';return}
 box.innerHTML=`<form class="badge-progress-request-form"><div class="field"><label>Brasão</label><select name="badge_id">${badges.map(b=>`<option value="${e(b.id)}">${e(b.name)}</option>`).join('')}</select></div><div class="field"><label>Total atual</label><input name="progress_value" type="number" min="0" step="1" required value="${current.get(badges[0].id)||0}"></div><div class="field span-full"><p class="badge-current-value"></p></div><div class="field span-full"><label>Justificativa / evidência <span class="muted">(opcional)</span></label><textarea name="note" rows="4" maxlength="1000" placeholder="Ex.: vitória no confronto da cena X, patrimônio atualizado, novo nível alcançado..."></textarea></div><div class="form-actions span-full"><button class="button" type="submit">Enviar para aprovação</button></div><p class="status span-full"></p></form>`;
 const form=box.querySelector('form'),sel=form.badge_id,input=form.progress_value,info=box.querySelector('.badge-current-value'),st=box.querySelector('.status');const sync=()=>{const v=current.get(sel.value)||0;info.textContent=`Progresso oficial atual: ${v}`;input.value=v};sel.onchange=sync;sync();form.onsubmit=async ev=>{ev.preventDefault();setStatus(st,'Enviando solicitação...');const{error}=await supabase.rpc('submit_badge_progress_request',{p_character_id:character.id,p_badge_id:sel.value,p_progress_value:Number(input.value||0),p_note:form.note.value.trim()||null});if(error)return setStatus(st,error.message,'error');setStatus(st,'Progresso enviado para aprovação.','success');form.querySelector('button[type="submit"]').disabled=true};
}

async function openCharacterBadgeManager(){
 if(!isAdmin)return;const modal=document.createElement('div');modal.className='modal-backdrop';modal.innerHTML=`<div class="modal-panel"><div class="modal-head"><div><span class="eyebrow">Administração</span><h2>Brasões de ${e(character.name)}</h2><p class="form-help">Registre ou atualize o progresso das conquistas vinculadas a este personagem.</p></div><button class="modal-close" type="button">×</button></div><div id="character-badge-manager"><p class="status">Carregando...</p></div></div>`;document.body.appendChild(modal);const close=()=>modal.remove();modal.querySelector('.modal-close').onclick=close;modal.addEventListener('click',ev=>{if(ev.target===modal)close()});const box=modal.querySelector('#character-badge-manager');
 const [br,pr]=await Promise.all([supabase.from('badges').select('*').eq('source_scope','character').order('name'),supabase.from('character_badge_progress').select('character_id,badge_id,progress_value').eq('character_id',character.id)]);if(br.error||pr.error){box.innerHTML=`<p class="status error">${e((br.error||pr.error).message)}</p>`;return}const badges=br.data||[],rows=pr.data||[];
 box.innerHTML=`<form class="badge-manager-grid"><div class="field" style="grid-column:span 2"><label>Brasão</label><select name="badge_id">${badges.map(b=>`<option value="${e(b.id)}">${e(b.name)}</option>`).join('')}</select></div><div class="field"><label>Progresso</label><input name="progress_value" type="number" min="0" value="0"></div><button class="button button-small" type="submit">Atribuir / atualizar</button></form><p class="status"></p><div class="badge-manager-current">${rows.map(r=>{const b=badges.find(x=>x.id===r.badge_id);return `<div class="badge-manager-item"><div><strong>${e(b?.name||'Brasão')}</strong><p>Progresso ${Number(r.progress_value||0)}</p></div><button type="button" class="post-delete" data-remove="${e(r.badge_id)}">Remover</button></div>`}).join('')||'<p class="profile-feed-empty">Nenhum progresso registrado.</p>'}</div>`;
 const form=box.querySelector('form'),status=box.querySelector('.status');form.onsubmit=async ev=>{ev.preventDefault();const payload={character_id:character.id,badge_id:form.badge_id.value,progress_value:Number(form.progress_value.value||0),updated_by:viewer.id},r=await supabase.from('character_badge_progress').upsert(payload,{onConflict:'character_id,badge_id'});if(r.error)return setStatus(status,r.error.message,'error');setStatus(status,'Brasão atualizado.','success');setTimeout(()=>{close();openCharacterBadgeManager()},250)};box.querySelectorAll('[data-remove]').forEach(btn=>btn.onclick=async()=>{if(!confirm('Remover este Brasão do personagem?'))return;const r=await supabase.from('character_badge_progress').delete().match({character_id:character.id,badge_id:btn.dataset.remove});if(r.error)return setStatus(status,r.error.message,'error');close();openCharacterBadgeManager()});
}
async function reloadEntries(renderAfter=true){const{data}=await supabase.from('character_content').select('*').eq('character_id',id).order('position').order('created_at');entries=data||[];if(renderAfter)render()}
async function loadExtras(){
 const [g,t,r,sc,f]=await Promise.all([
  supabase.from('character_gallery').select('*').eq('character_id',id).order('position'),
  supabase.from('character_tags').select('tag').eq('character_id',id).order('tag'),
  supabase.from('character_relations').select('*,source:characters!character_relations_source_character_id_fkey(id,name),target:characters!character_relations_target_character_id_fkey(id,name)').or(`source_character_id.eq.${id},target_character_id.eq.${id}`),
  supabase.from('scene_characters').select('scene_id,display_order,scene:scenes(id,title,summary,scene_url,scene_date,created_at)').eq('character_id',id),
  viewer?supabase.from('favorites').select('target_id').eq('user_id',viewer.id).eq('target_type','character').eq('target_id',id).maybeSingle():Promise.resolve({data:null})
 ]);
 let scenes=(sc.data||[]).filter(x=>x.scene);
 const sortMode=character.scene_sort_mode||'custom';
 const dateOf=x=>new Date(x.scene.scene_date||x.scene.created_at||0).getTime();
 if(sortMode==='newest') scenes.sort((a,b)=>dateOf(b)-dateOf(a));
 else if(sortMode==='oldest') scenes.sort((a,b)=>dateOf(a)-dateOf(b));
 else scenes.sort((a,b)=>(a.display_order??999999)-(b.display_order??999999)||dateOf(a)-dateOf(b));
 const sceneRows=scenes.map((x,i)=>`<article class="scene-row ${canManage()&&sortMode==='custom'?'scene-sortable':''}" data-scene-id="${e(x.scene.id)}" draggable="${canManage()&&sortMode==='custom'?'true':'false'}"><div class="scene-row-head">${canManage()&&sortMode==='custom'?`<span class="scene-drag" title="Arraste para reordenar" aria-label="Arraste para reordenar">⋮⋮</span>`:''}<strong>${e(x.scene.title)}</strong>${canManage()?`<span class="scene-actions"><button type="button" class="post-edit" data-edit-scene="${e(x.scene.id)}">Editar</button><button type="button" class="post-delete" data-delete-scene="${e(x.scene.id)}">Excluir</button></span>`:''}</div><span>${e(x.scene.summary||'')}</span>${x.scene.scene_date?`<small>${new Date(x.scene.scene_date+'T12:00:00').toLocaleDateString('pt-BR')}</small>`:''}${ext(x.scene.scene_url)?`<a href="${e(ext(x.scene.scene_url))}" target="_blank" rel="noopener">Abrir cena ↗</a>`:''}</article>`).join('');
 const sec=document.createElement('section');sec.className='section character-community';sec.innerHTML=`<div class="section-heading"><span class="eyebrow">Arquivo vivo</span><h2>Registros & Conexões</h2></div>
 ${viewer?`<button id="favorite-character" class="button button-small">${f.data?'★ Na Coleção':'☆ Adicionar à Coleção'}</button>${viewer?.id===character.owner_id?`<button id="feature-character" class="button button-small">Definir como personagem principal</button>`:''}`:''}
 ${(t.data||[]).length?`<div class="chip-row">${t.data.map(x=>`<span class="tag-chip">#${e(x.tag)}</span>`).join('')}</div>`:''}
 <div class="community-grid"><div><h3>Relações</h3>${(r.data||[]).filter(x=>x.status==='confirmed').map(x=>{const other=x.source_character_id===id?x.target:x.source;return `<a class="relation-row" href="personagem.html?id=${other.id}"><strong>${e(other.name)}</strong><span>${e(x.label||x.relation_type)}</span></a>`}).join('')||'<p class="profile-feed-empty">Nenhuma relação confirmada.</p>'}${viewer?.id===character.owner_id?(r.data||[]).filter(x=>x.status==='pending'&&x.target_character_id===id).map(x=>`<div class="relation-pending"><span>${e(x.source?.name)} propôs: ${e(x.label||x.relation_type)}</span><button class="post-edit" data-confirm-relation="${x.id}">Confirmar</button></div>`).join(''):''}</div>
 <div><div class="scene-section-head"><h3>Cenas</h3>${canManage()?`<label class="scene-sort-control">Exibição <select id="scene-sort-mode"><option value="custom" ${sortMode==='custom'?'selected':''}>Personalizada</option><option value="newest" ${sortMode==='newest'?'selected':''}>Mais recentes</option><option value="oldest" ${sortMode==='oldest'?'selected':''}>Mais antigas</option></select></label>`:''}</div><div id="scene-list">${sceneRows||'<p class="profile-feed-empty">Nenhuma cena registrada.</p>'}</div></div></div>
 ${(g.data||[]).length?`<div><h3>Galeria</h3><div class="organic-gallery character-gallery">${g.data.map(x=>`<figure><img src="${e(x.image_url)}" alt="${e(x.caption||character.name)}" loading="lazy">${x.caption?`<figcaption>${e(x.caption)}</figcaption>`:''}${canManage()?`<button type="button" class="gallery-delete" data-delete-gallery="${e(x.id)}" aria-label="Excluir imagem" title="Excluir imagem">×</button>`:''}</figure>`).join('')}</div></div>`:''}
 ${canManage()?`<form id="gallery-form" class="inline-community-form"><h3>Adicionar à Galeria</h3><input name="image_url" type="url" required placeholder="URL pública da imagem"><input name="caption" maxlength="160" placeholder="Legenda (opcional)"><button class="button button-small">Adicionar imagem</button><p class="status"></p></form><form id="relation-form" class="inline-community-form"><h3>Propor relação</h3><div class="character-autocomplete"><input name="target_search" autocomplete="off" required placeholder="Busque pelo nome ou alcunha do personagem"><input name="target" type="hidden"><div class="character-autocomplete-results" hidden></div></div><input name="label" required maxlength="60" placeholder="Ex.: Rival, Aliado, Mentor..."><button class="button button-small" type="submit" disabled>Enviar relação</button><p class="status"></p></form><form id="scene-form" class="inline-community-form"><h3>Registrar cena</h3><input name="title" required maxlength="160" placeholder="Título da cena"><input name="scene_date" type="date" aria-label="Data da cena"><input name="scene_url" placeholder="Link da cena (opcional)"><textarea name="summary" rows="3" placeholder="Resuma o que aconteceu nesta cena."></textarea><button class="button button-small">Adicionar ao histórico</button><p class="status"></p></form>`:''}`;
 root.appendChild(sec);
 document.querySelector('#feature-character')?.addEventListener('click',async()=>{const{error}=await supabase.rpc('set_featured_character',{p_character_id:id});if(error)alert(error.message);else alert('Personagem definido como principal.')});
 document.querySelector('#favorite-character')?.addEventListener('click',async ev=>{const exists=!!f.data;const rr=exists?await supabase.from('favorites').delete().match({user_id:viewer.id,target_type:'character',target_id:id}):await supabase.from('favorites').insert({user_id:viewer.id,target_type:'character',target_id:id});if(!rr.error){f.data=exists?null:{target_id:id};ev.currentTarget.textContent=exists?'☆ Adicionar à Coleção':'★ Na Coleção'}});
 document.querySelectorAll('[data-confirm-relation]').forEach(b=>b.onclick=async()=>{const{error}=await supabase.from('character_relations').update({status:'confirmed',confirmed_by:viewer.id}).eq('id',b.dataset.confirmRelation);if(error)alert(error.message);else location.reload()});
 document.querySelectorAll('[data-delete-gallery]').forEach(b=>b.onclick=async()=>{if(!confirm('Remover esta imagem da galeria?'))return;const{error}=await supabase.from('character_gallery').delete().eq('id',b.dataset.deleteGallery);if(error)return alert(error.message);location.reload()});
 document.querySelector('#gallery-form')?.addEventListener('submit',async ev=>{ev.preventDefault();const form=ev.currentTarget,st=form.querySelector('.status');const{error}=await supabase.from('character_gallery').insert({character_id:id,image_url:form.image_url.value.trim(),caption:form.caption.value.trim()||null,added_by:viewer.id});setStatus(st,error?error.message:'Imagem adicionada à galeria.',error?'error':'success');if(!error)setTimeout(()=>location.reload(),400)});
 const relationForm=document.querySelector('#relation-form');
 if(relationForm){const input=relationForm.target_search,hidden=relationForm.target,results=relationForm.querySelector('.character-autocomplete-results'),submit=relationForm.querySelector('button[type="submit"]');let timer,seq=0;input.addEventListener('input',()=>{hidden.value='';submit.disabled=true;clearTimeout(timer);const raw=input.value.trim(),q=raw.replace(/^@+/, '').trim();if(q.length<2){results.hidden=true;results.innerHTML='';return}results.innerHTML='<p>Buscando personagens...</p>';results.hidden=false;const request=++seq;timer=setTimeout(async()=>{const like=`%${q}%`;const{data,error}=await supabase.from('characters').select('id,name,nickname').eq('status','approved').neq('id',id).or(`name.ilike.${like},nickname.ilike.${like}`).order('name').limit(8);if(request!==seq)return;if(error){results.innerHTML=`<p class="status error">Não foi possível buscar personagens: ${e(error.message)}</p>`;results.hidden=false;return}results.innerHTML=(data||[]).map(c=>`<button type="button" data-pick-character="${e(c.id)}" data-name="${e(c.name)}"><strong>${e(c.name)}</strong>${c.nickname?`<span>${e(c.nickname)}</span>`:''}</button>`).join('')||'<p>Nenhum personagem encontrado.</p>';results.hidden=false;results.querySelectorAll('[data-pick-character]').forEach(b=>b.onclick=()=>{hidden.value=b.dataset.pickCharacter;input.value=b.dataset.name;submit.disabled=false;results.hidden=true})},220)});input.addEventListener('focus',()=>{if(results.innerHTML&&input.value.trim().length>=2)results.hidden=false});input.addEventListener('blur',()=>setTimeout(()=>results.hidden=true,180));relationForm.addEventListener('submit',async ev=>{ev.preventDefault();ev.stopPropagation();const st=relationForm.querySelector('.status');if(!hidden.value)return setStatus(st,'Selecione um personagem nos resultados da busca.','error');const targetId=hidden.value,label=relationForm.label.value.trim();submit.disabled=true;submit.classList.add('is-busy');submit.setAttribute('aria-busy','true');setStatus(st,'Enviando relação...');try{const operation=supabase.from('character_relations').insert({source_character_id:id,target_character_id:targetId,relation_type:'custom',label,created_by:viewer.id});const timeout=new Promise((_,reject)=>setTimeout(()=>reject(new Error('A solicitação demorou mais que o esperado. Tente novamente.')),12000));const{error}=await Promise.race([operation,timeout]);if(error)throw error;setStatus(st,'Relação enviada. O outro jogador deverá confirmá-la.','success');relationForm.reset();hidden.value='';results.hidden=true;submit.disabled=true}catch(error){setStatus(st,error?.message||'Não foi possível enviar a relação.','error');submit.disabled=false}finally{submit.classList.remove('is-busy');submit.removeAttribute('aria-busy')}})}
 document.querySelector('#scene-form')?.addEventListener('submit',async ev=>{ev.preventDefault();const form=ev.currentTarget,st=form.querySelector('.status');const {data:scene,error}=await supabase.from('scenes').insert({title:form.title.value.trim(),summary:form.summary.value.trim()||null,scene_url:form.scene_url.value.trim()||null,scene_date:form.scene_date.value||null,created_by:viewer.id}).select('id').single();if(error)return setStatus(st,error.message,'error');const maxOrder=scenes.reduce((m,x)=>Math.max(m,Number(x.display_order??-1)), -1)+1;const j=await supabase.from('scene_characters').insert({scene_id:scene.id,character_id:id,display_order:maxOrder});setStatus(st,j.error?j.error.message:'Cena adicionada ao histórico.',j.error?'error':'success');if(!j.error)setTimeout(()=>location.reload(),350)});
 document.querySelectorAll('[data-edit-scene]').forEach(b=>b.onclick=async()=>{const row=scenes.find(x=>x.scene.id===b.dataset.editScene);if(!row)return;const title=prompt('Título da cena:',row.scene.title);if(title===null||!title.trim())return;const summary=prompt('Resumo da cena:',row.scene.summary||'');if(summary===null)return;const url=prompt('Link da cena (opcional):',row.scene.scene_url||'');if(url===null)return;const date=prompt('Data da cena (AAAA-MM-DD, opcional):',row.scene.scene_date||'');if(date===null)return;const{error}=await supabase.from('scenes').update({title:title.trim(),summary:summary.trim()||null,scene_url:url.trim()||null,scene_date:date.trim()||null}).eq('id',row.scene.id);if(error)return alert(error.message);location.reload()});
 document.querySelectorAll('[data-delete-scene]').forEach(b=>b.onclick=async()=>{const row=scenes.find(x=>x.scene.id===b.dataset.deleteScene);if(!row||!confirm(`Excluir a cena "${row.scene.title}" deste personagem?`))return;const unlink=await supabase.from('scene_characters').delete().match({scene_id:row.scene.id,character_id:id});if(unlink.error)return alert(unlink.error.message);const{count}=await supabase.from('scene_characters').select('scene_id',{count:'exact',head:true}).eq('scene_id',row.scene.id);if(!count)await supabase.from('scenes').delete().eq('id',row.scene.id);location.reload()});
 document.querySelector('#scene-sort-mode')?.addEventListener('change',async ev=>{const{error}=await supabase.from('characters').update({scene_sort_mode:ev.target.value}).eq('id',id);if(error){alert(error.message);return}location.reload()});
 if(canManage()&&sortMode==='custom'){const list=document.querySelector('#scene-list');let dragging=null;list?.querySelectorAll('.scene-sortable').forEach(row=>{row.addEventListener('dragstart',()=>{dragging=row;row.classList.add('dragging')});row.addEventListener('dragend',async()=>{row.classList.remove('dragging');dragging=null;const ordered=[...list.querySelectorAll('.scene-sortable')];const updates=ordered.map((el,pos)=>supabase.from('scene_characters').update({display_order:pos}).match({scene_id:el.dataset.sceneId,character_id:id}));const res=await Promise.all(updates);const bad=res.find(x=>x.error);if(bad)alert(bad.error.message)});row.addEventListener('dragover',ev=>{ev.preventDefault();if(!dragging||dragging===row)return;const rect=row.getBoundingClientRect();list.insertBefore(dragging,ev.clientY<rect.top+rect.height/2?row:row.nextSibling)})})}
}

load();