-- Tales of Vanity — Publicações estruturadas + menções/notificações

ALTER TABLE public.profile_posts
  ADD COLUMN IF NOT EXISTS title text,
  ADD COLUMN IF NOT EXISTS is_structured boolean NOT NULL DEFAULT false;

ALTER TABLE public.profile_posts
  DROP CONSTRAINT IF EXISTS profile_posts_content_length_check;
ALTER TABLE public.profile_posts
  DROP CONSTRAINT IF EXISTS profile_posts_content_check;
-- Remove o limite antigo de 10.000, independentemente do nome gerado da constraint.
DO $$
DECLARE r record;
BEGIN
  FOR r IN
    SELECT conname
    FROM pg_constraint
    WHERE conrelid = 'public.profile_posts'::regclass
      AND contype = 'c'
      AND pg_get_constraintdef(oid) ILIKE '%char_length(content)%'
  LOOP
    EXECUTE format('ALTER TABLE public.profile_posts DROP CONSTRAINT %I', r.conname);
  END LOOP;
END $$;

ALTER TABLE public.profile_posts
  ADD CONSTRAINT profile_posts_content_max_100k
  CHECK (content IS NULL OR char_length(content) <= 100000);
ALTER TABLE public.profile_posts
  ADD CONSTRAINT profile_posts_title_max_160
  CHECK (title IS NULL OR char_length(title) <= 160);
ALTER TABLE public.profile_posts
  ADD CONSTRAINT profile_posts_wall_simple
  CHECK (post_type <> 'wall' OR is_structured = false);

CREATE TABLE IF NOT EXISTS public.profile_post_sections (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id uuid NOT NULL REFERENCES public.profile_posts(id) ON DELETE CASCADE,
  parent_id uuid REFERENCES public.profile_post_sections(id) ON DELETE CASCADE,
  title text NOT NULL CHECK (char_length(title) BETWEEN 1 AND 160),
  content text CHECK (content IS NULL OR char_length(content) <= 100000),
  position integer NOT NULL DEFAULT 0 CHECK (position >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS profile_post_sections_post_idx ON public.profile_post_sections(post_id, position);
CREATE INDEX IF NOT EXISTS profile_post_sections_parent_idx ON public.profile_post_sections(parent_id, position);
ALTER TABLE public.profile_post_sections ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.profile_post_sections TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.profile_post_sections TO authenticated;

DROP POLICY IF EXISTS "profile_post_sections_public_read" ON public.profile_post_sections;
CREATE POLICY "profile_post_sections_public_read" ON public.profile_post_sections
FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "profile_post_sections_author_insert" ON public.profile_post_sections;
CREATE POLICY "profile_post_sections_author_insert" ON public.profile_post_sections
FOR INSERT TO authenticated WITH CHECK (
  EXISTS (SELECT 1 FROM public.profile_posts p WHERE p.id = post_id AND p.author_id = auth.uid() AND p.post_type = 'personal')
);

DROP POLICY IF EXISTS "profile_post_sections_author_update" ON public.profile_post_sections;
CREATE POLICY "profile_post_sections_author_update" ON public.profile_post_sections
FOR UPDATE TO authenticated USING (
  EXISTS (SELECT 1 FROM public.profile_posts p WHERE p.id = post_id AND p.author_id = auth.uid())
) WITH CHECK (
  EXISTS (SELECT 1 FROM public.profile_posts p WHERE p.id = post_id AND p.author_id = auth.uid())
);

DROP POLICY IF EXISTS "profile_post_sections_delete_allowed" ON public.profile_post_sections;
CREATE POLICY "profile_post_sections_delete_allowed" ON public.profile_post_sections
FOR DELETE TO authenticated USING (
  EXISTS (SELECT 1 FROM public.profile_posts p WHERE p.id = post_id AND (p.author_id = auth.uid() OR public.is_admin()))
);

-- Permite ao autor atualizar a própria publicação (útil para documentos estruturados).
GRANT UPDATE ON public.profile_posts TO authenticated;
DROP POLICY IF EXISTS "profile_posts_author_update" ON public.profile_posts;
CREATE POLICY "profile_posts_author_update" ON public.profile_posts
FOR UPDATE TO authenticated USING (author_id = auth.uid())
WITH CHECK (author_id = auth.uid() AND (post_type <> 'personal' OR profile_id = auth.uid()));

CREATE TABLE IF NOT EXISTS public.mention_notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mentioned_user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  mentioned_by uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  post_id uuid NOT NULL REFERENCES public.profile_posts(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  read_at timestamptz,
  UNIQUE (mentioned_user_id, post_id)
);
CREATE INDEX IF NOT EXISTS mention_notifications_user_idx ON public.mention_notifications(mentioned_user_id, created_at DESC);
ALTER TABLE public.mention_notifications ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.mention_notifications TO authenticated;
GRANT UPDATE (read_at) ON public.mention_notifications TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.mention_notifications_id_seq TO authenticated;

DROP POLICY IF EXISTS "mentions_own_read" ON public.mention_notifications;
CREATE POLICY "mentions_own_read" ON public.mention_notifications
FOR SELECT TO authenticated USING (mentioned_user_id = auth.uid());
DROP POLICY IF EXISTS "mentions_own_update" ON public.mention_notifications;
CREATE POLICY "mentions_own_update" ON public.mention_notifications
FOR UPDATE TO authenticated USING (mentioned_user_id = auth.uid())
WITH CHECK (mentioned_user_id = auth.uid());

-- As notificações são geradas no banco; o navegador não pode forjá-las.
CREATE OR REPLACE FUNCTION public.sync_post_mentions(p_post_id uuid, p_text text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_author uuid;
BEGIN
  SELECT author_id INTO v_author FROM public.profile_posts WHERE id = p_post_id;
  IF v_author IS NULL THEN RETURN; END IF;

  INSERT INTO public.mention_notifications (mentioned_user_id, mentioned_by, post_id)
  SELECT DISTINCT p.id, v_author, p_post_id
  FROM regexp_matches(lower(coalesce(p_text,'')), '@([a-z0-9._-]{3,30})', 'g') AS m(match)
  JOIN public.profiles p ON lower(p.username) = m.match[1]
  WHERE p.active = true AND p.id <> v_author
  ON CONFLICT (mentioned_user_id, post_id) DO NOTHING;
END;
$$;

CREATE OR REPLACE FUNCTION public.profile_posts_mentions_trigger()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  PERFORM public.sync_post_mentions(NEW.id, concat_ws(E'\n', NEW.title, NEW.content));
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_profile_posts_mentions ON public.profile_posts;
CREATE TRIGGER trg_profile_posts_mentions
AFTER INSERT OR UPDATE OF title, content ON public.profile_posts
FOR EACH ROW EXECUTE FUNCTION public.profile_posts_mentions_trigger();

CREATE OR REPLACE FUNCTION public.profile_sections_mentions_trigger()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  PERFORM public.sync_post_mentions(NEW.post_id, concat_ws(E'\n', NEW.title, NEW.content));
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_profile_sections_mentions ON public.profile_post_sections;
CREATE TRIGGER trg_profile_sections_mentions
AFTER INSERT OR UPDATE OF title, content ON public.profile_post_sections
FOR EACH ROW EXECUTE FUNCTION public.profile_sections_mentions_trigger();
