-- Tales of Vanity — Perfil social (Publicações + Mural + imagens)
-- Execute este arquivo inteiro no SQL Editor do Supabase.

CREATE TABLE IF NOT EXISTS public.profile_posts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  author_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  profile_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  post_type text NOT NULL CHECK (post_type IN ('personal', 'wall')),
  content text CHECK (content IS NULL OR char_length(content) <= 10000),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT profile_posts_personal_owner_check CHECK (post_type <> 'personal' OR author_id = profile_id),
  CONSTRAINT profile_posts_has_content CHECK (content IS NOT NULL OR post_type IN ('personal','wall'))
);

CREATE INDEX IF NOT EXISTS profile_posts_profile_created_idx ON public.profile_posts(profile_id, created_at DESC);
CREATE INDEX IF NOT EXISTS profile_posts_author_idx ON public.profile_posts(author_id);

CREATE TABLE IF NOT EXISTS public.profile_post_images (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id uuid NOT NULL REFERENCES public.profile_posts(id) ON DELETE CASCADE,
  storage_path text NOT NULL UNIQUE,
  public_url text NOT NULL,
  position smallint NOT NULL DEFAULT 0 CHECK (position BETWEEN 0 AND 3),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS profile_post_images_post_idx ON public.profile_post_images(post_id, position);

ALTER TABLE public.profile_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_post_images ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON public.profile_posts, public.profile_post_images TO anon, authenticated;
GRANT INSERT, DELETE ON public.profile_posts, public.profile_post_images TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.profile_post_images_id_seq TO authenticated;

DROP POLICY IF EXISTS "profile_posts_public_read" ON public.profile_posts;
CREATE POLICY "profile_posts_public_read" ON public.profile_posts FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "profile_posts_authenticated_insert" ON public.profile_posts;
CREATE POLICY "profile_posts_authenticated_insert" ON public.profile_posts FOR INSERT TO authenticated
WITH CHECK (
  auth.uid() = author_id
  AND EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.active = true)
  AND (
    (post_type = 'personal' AND profile_id = auth.uid())
    OR (post_type = 'wall' AND profile_id <> auth.uid())
  )
);

DROP POLICY IF EXISTS "profile_posts_delete_author_owner_admin" ON public.profile_posts;
CREATE POLICY "profile_posts_delete_author_owner_admin" ON public.profile_posts FOR DELETE TO authenticated
USING (auth.uid() = author_id OR auth.uid() = profile_id OR public.is_admin());

DROP POLICY IF EXISTS "profile_post_images_public_read" ON public.profile_post_images;
CREATE POLICY "profile_post_images_public_read" ON public.profile_post_images FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "profile_post_images_author_insert" ON public.profile_post_images;
CREATE POLICY "profile_post_images_author_insert" ON public.profile_post_images FOR INSERT TO authenticated
WITH CHECK (EXISTS (SELECT 1 FROM public.profile_posts p WHERE p.id = post_id AND p.author_id = auth.uid()));

DROP POLICY IF EXISTS "profile_post_images_delete_allowed" ON public.profile_post_images;
CREATE POLICY "profile_post_images_delete_allowed" ON public.profile_post_images FOR DELETE TO authenticated
USING (EXISTS (SELECT 1 FROM public.profile_posts p WHERE p.id = post_id AND (p.author_id = auth.uid() OR p.profile_id = auth.uid() OR public.is_admin())));

-- Bucket público para as fotos das publicações.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('profile-posts', 'profile-posts', true, 5242880, ARRAY['image/jpeg','image/png','image/webp','image/gif'])
ON CONFLICT (id) DO UPDATE SET public = true, file_size_limit = 5242880, allowed_mime_types = ARRAY['image/jpeg','image/png','image/webp','image/gif'];

DROP POLICY IF EXISTS "profile_posts_storage_insert" ON storage.objects;
CREATE POLICY "profile_posts_storage_insert" ON storage.objects FOR INSERT TO authenticated
WITH CHECK (bucket_id = 'profile-posts' AND (storage.foldername(name))[1] = auth.uid()::text);

DROP POLICY IF EXISTS "profile_posts_storage_delete_own" ON storage.objects;
CREATE POLICY "profile_posts_storage_delete_own" ON storage.objects FOR DELETE TO authenticated
USING (bucket_id = 'profile-posts' AND ((storage.foldername(name))[1] = auth.uid()::text OR public.is_admin()));
